---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/redis-server --version
      register: redis_test_output
    - name: redis-server --version
      debug:
        msg: '{{ redis_test_output.stdout }}'
