---
- name: Testing andrewrothstein.redis
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'redis-server --version'
      ansible.builtin.command: /usr/local/bin/redis-server --version
      changed_when: false
      register: redis_test_output
    - name: Output from 'redis-server --version'
      ansible.builtin.debug:
        msg: '{{ redis_test_output.stdout }}'
