---
- name: Installing andrewrothstien.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.gcc_toolbox
  ansible.builtin.include_role:
    name: andrewrothstein.gcc_toolbox
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Install dep pkgs...
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ redis_dep_pkgs | default([]) }}'
    state: present

- name: Check for install at {{ redis_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ redis_install_exe }}'
  changed_when: false
  register: redis_binary
- name: Downloading, building, installing redis
  when: not redis_binary.stat.exists
  block:
    - name: Downloading {{ redis_tgz_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ redis_tgz_url }}'
        checksum: '{{ redis_checksum }}'
        dest: '{{ redis_tmp_tgz }}'
        mode: '644'

    - name: Unarchive {{ redis_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ redis_tmp_tgz }}'
        dest: '{{ redis_parent_src_dir }}'
        creates: '{{ redis_src_dir }}'

    - name: Make in {{ redis_src_dir }}
      become: true
      become_user: root
      ansible.builtin.command: make
      args:
        chdir: '{{ redis_src_dir }}'
        creates: '{{ redis_src_dir }}/src/redis-server'

    - name: Make install in {{ redis_src_dir }}
      become: true
      become_user: root
      ansible.builtin.command: make install
      args:
        chdir: '{{ redis_src_dir }}'
        creates: '{{ redis_install_exe }}'
  always:
    - name: Cleanup
      become: true
      become_user: root
      with_items:
        - '{{ redis_src_dir }}'
        - '{{ redis_tmp_tgz }}'
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
